# Generated by Django 5.2.5 on 2025-08-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='convertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('from_currancy', models.CharField()),
                ('to_currancy', models.CharField()),
                ('converted_amont', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
